{"tag": "runnerRuntimeLog", "value": {"content": "[rpc]connected"}, "ts": 1535651240.4295297}
{"tag": "assertion", "value": {"method": "assert", "type": "True", "args": [false], "msg": "Failed to enter Gizmos building", "lineno": null, "srcfilename": null}, "ts": 1535651264.7193274}
{"tag": "assertion", "value": {"method": "fail", "errmsg": "False is not true : Failed to enter Gizmos building", "msg": "False is not true : Failed to enter Gizmos building", "traceback": "Traceback: (failure cause)\n  File \"MenuBar.py\", line 172, in <module>\n    pocounit.main()\n  File \"C:\\Users\\Owner\\AppData\\Local\\Programs\\Python\\Python36\\lib\\site-packages\\pocounit\\__init__.py\", line 45, in main\n    result = runner.run(suite)\n  File \"C:\\Users\\Owner\\AppData\\Local\\Programs\\Python\\Python36\\lib\\unittest\\runner.py\", line 176, in run\n    test(result)\n  File \"C:\\Users\\Owner\\AppData\\Local\\Programs\\Python\\Python36\\lib\\unittest\\suite.py\", line 84, in __call__\n    return self.run(*args, **kwds)\n  File \"C:\\Users\\Owner\\AppData\\Local\\Programs\\Python\\Python36\\lib\\site-packages\\pocounit\\suite.py\", line 15, in run\n    super(PocoTestSuite, self).run(result, debug)\n  File \"C:\\Users\\Owner\\AppData\\Local\\Programs\\Python\\Python36\\lib\\unittest\\suite.py\", line 122, in run\n    test(result)\n  File \"C:\\Users\\Owner\\AppData\\Local\\Programs\\Python\\Python36\\lib\\unittest\\case.py\", line 653, in __call__\n    return self.run(*args, **kwds)\n  File \"C:\\Users\\Owner\\AppData\\Local\\Programs\\Python\\Python36\\lib\\site-packages\\pocounit\\case.py\", line 201, in run\n    ret = self._super_run_modified(result)\n  File \"C:\\Users\\Owner\\AppData\\Local\\Programs\\Python\\Python36\\lib\\site-packages\\pocounit\\case.py\", line 262, in _super_run_modified\n    testMethod()\n  File \"MenuBar.py\", line 137, in runTest\n    self.testGizmos()\n  File \"MenuBar.py\", line 87, in testGizmos\n    \"Failed to enter Gizmos building\")\n  File \"c:\\users\\owner\\desktop\\eric\\quirk-uitest\\testflow\\lib\\case\\unity_game.py\", line 52, in check\n    self.assertTrue(exists(template), msg)\n  File \"C:\\Users\\Owner\\AppData\\Local\\Programs\\Python\\Python36\\lib\\site-packages\\pocounit\\case.py\", line 382, in assertTrue\n    self.fail(msg)\n  File \"C:\\Users\\Owner\\AppData\\Local\\Programs\\Python\\Python36\\lib\\site-packages\\pocounit\\case.py\", line 371, in fail\n    .format(''.join(traceback.format_stack()), err_typename, fail_msg))\nAssertionError: False is not true : Failed to enter Gizmos building", "lineno": null, "srcfilename": null}, "ts": 1535651264.7292154}
{"tag": "assertion", "value": {"method": "assert", "type": "Equal", "args": [[], ["False is not true : Failed to enter Gizmos building"]], "msg": null, "lineno": null, "srcfilename": null}, "ts": 1535651272.529597}
{"tag": "assertion", "value": {"method": "fail", "errmsg": "Lists differ: [] != ['False is not true : Failed to enter Gizmos building']\n\nSecond list contains 1 additional elements.\nFirst extra element 0:\n'False is not true : Failed to enter Gizmos building'\n\n- []\n+ ['False is not true : Failed to enter Gizmos building']", "msg": "Lists differ: [] != ['False is not true : Failed to enter Gizmos building']\n\nSecond list contains 1 additional elements.\nFirst extra element 0:\n'False is not true : Failed to enter Gizmos building'\n\n- []\n+ ['False is not true : Failed to enter Gizmos building']", "traceback": "Traceback: (failure cause)\n  File \"MenuBar.py\", line 172, in <module>\n    pocounit.main()\n  File \"C:\\Users\\Owner\\AppData\\Local\\Programs\\Python\\Python36\\lib\\site-packages\\pocounit\\__init__.py\", line 45, in main\n    result = runner.run(suite)\n  File \"C:\\Users\\Owner\\AppData\\Local\\Programs\\Python\\Python36\\lib\\unittest\\runner.py\", line 176, in run\n    test(result)\n  File \"C:\\Users\\Owner\\AppData\\Local\\Programs\\Python\\Python36\\lib\\unittest\\suite.py\", line 84, in __call__\n    return self.run(*args, **kwds)\n  File \"C:\\Users\\Owner\\AppData\\Local\\Programs\\Python\\Python36\\lib\\site-packages\\pocounit\\suite.py\", line 15, in run\n    super(PocoTestSuite, self).run(result, debug)\n  File \"C:\\Users\\Owner\\AppData\\Local\\Programs\\Python\\Python36\\lib\\unittest\\suite.py\", line 122, in run\n    test(result)\n  File \"C:\\Users\\Owner\\AppData\\Local\\Programs\\Python\\Python36\\lib\\unittest\\case.py\", line 653, in __call__\n    return self.run(*args, **kwds)\n  File \"C:\\Users\\Owner\\AppData\\Local\\Programs\\Python\\Python36\\lib\\site-packages\\pocounit\\case.py\", line 201, in run\n    ret = self._super_run_modified(result)\n  File \"C:\\Users\\Owner\\AppData\\Local\\Programs\\Python\\Python36\\lib\\site-packages\\pocounit\\case.py\", line 271, in _super_run_modified\n    self.tearDown()\n  File \"MenuBar.py\", line 24, in tearDown\n    self.assertEqual([], self.assertErrors)\n  File \"C:\\Users\\Owner\\AppData\\Local\\Programs\\Python\\Python36\\lib\\site-packages\\pocounit\\case.py\", line 396, in assertEqual\n    return super(PocoTestCase, self).assertEqual(first, second, msg)\n  File \"C:\\Users\\Owner\\AppData\\Local\\Programs\\Python\\Python36\\lib\\unittest\\case.py\", line 829, in assertEqual\n    assertion_func(first, second, msg=msg)\n  File \"C:\\Users\\Owner\\AppData\\Local\\Programs\\Python\\Python36\\lib\\unittest\\case.py\", line 1028, in assertListEqual\n    self.assertSequenceEqual(list1, list2, msg, seq_type=list)\n  File \"C:\\Users\\Owner\\AppData\\Local\\Programs\\Python\\Python36\\lib\\unittest\\case.py\", line 1010, in assertSequenceEqual\n    self.fail(msg)\n  File \"C:\\Users\\Owner\\AppData\\Local\\Programs\\Python\\Python36\\lib\\site-packages\\pocounit\\case.py\", line 371, in fail\n    .format(''.join(traceback.format_stack()), err_typename, fail_msg))\nAssertionError: Lists differ: [] != ['False is not true : Failed to enter Gizmos building']\n\nSecond list contains 1 additional elements.\nFirst extra element 0:\n'False is not true : Failed to enter Gizmos building'\n\n- []\n+ ['False is not true : Failed to enter Gizmos building']", "lineno": null, "srcfilename": null}, "ts": 1535651272.5331473}
